name: Deploy to Live Channel

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "package.json"

jobs:
  deploy_live_website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm install
      - run: npm run build
      # Add any build steps here. For example:
      # - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_PLAYLIST_VIEW_SORTER }}"
          projectId: playlist-view-sorter
          channelId: live
